services:

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: master2
    ports:
      - 3306:3306

  pma:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
     - 3000:3000
